
title: Camino Couple
email: melvitax@me.com
description: >- 
  Melvin & Lilia's Travel 
baseurl: "" 
url: "" 
twitter_username: jekyllrb
github_username:  jekyll


#theme: minima
plugins:
  - jekyll-feed


exclude:
  - changelog.md
  - LICENSE.txt, 
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
