theme: jekyll-theme-minimal
title: "Camino Couple - Melvin & Lilia's Travel Vlog"
description: "Come walk with us as we explore the world of Camino de Santiago. This was our documented journey - Melvin and Lilia Rivera."
